[tool.ruff]
line-length = 79
target-version = "py310"
extend-exclude = ["tests/data", "docs"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "NPY", "D"]
ignore = [
    "E501",    # line too long
    "D100",    # missing module docstring
    "D101",    # missing class docstring
    "D102",    # missing method docstring
    "D203",    # ignore D203 to allow D211
    "D213"     # ignore D213 to allow D212
]

[tool.ruff.lint.isort]
known-first-party = ["macrohet"]
force-single-line = false
combine-as-imports = true

[tool.black]
line-length = 79
target-version = ["py310"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
disallow_untyped_defs = false
follow_imports = "silent"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
